[package]
name = "filcrypto"
description = "FFI Interface to Filecoin Proofs"
version = "0.7.5"
authors = [
  "nemo <nemo@protocol.ai>",
  "dignifiedquire <me@dignifiedquire.com>",
  "laser <l@s3r.com>"
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/filecoin-project/filecoin-ffi"
readme = "README.md"
edition = "2018"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
bls-signatures = { version = "0.10.0", default-features = false, features = ["blst"] }
blstrs = { version = "0.3" }
mimalloc = { version = "*", default-features = false }
byteorder = "1.2"
drop_struct_macro_derive = "0.5.0"
ff = { version = "0.3.1", package = "fff" }
ffi-toolkit = "0.5.0"
filepath = "0.1.1"
groupy = "0.4.1"
libc = "0.2.58"
log = "0.4.7"
fil_logger = "0.1.0"
rand = "0.7"
rand_chacha = "0.2.1"
rayon = "1.2.1"
anyhow = "1.0.23"
bellperson = { version = "0.15", default-features = false }
serde_json = "1.0.46"
rust-gpu-tools = "0.3"
storage-proofs-porep = { version = "~9.0.1", default-features = false }

[dependencies.filecoin-proofs-api]
package = "filecoin-proofs-api"
# git = "https://github.com/filecoin-project/rust-filecoin-proofs-api"
# rev = "v9.0.0-revert-deps-hotfix"
version = "9.0.0"
default-features = false

[build-dependencies]
cbindgen = "= 0.14.0"

[dev-dependencies]
tempfile = "3.0.8"

[features]
default = ["blst", "gpu", "multicore-sdr" ]
pairing = ["filecoin-proofs-api/pairing", "bellperson/pairing", "storage-proofs-porep/pairing"]
blst = ["filecoin-proofs-api/blst", "bellperson/blst", "storage-proofs-porep/blst"]
blst-portable = ["bls-signatures/blst-portable", "blstrs/portable"]
gpu = ["filecoin-proofs-api/gpu", "bellperson/gpu", "storage-proofs-porep/gpu"]
multicore-sdr = ["storage-proofs-porep/multicore-sdr"]

[patch.crates-io]
#storage-proofs-core = { git = "https://github.com/filecoin-project/rust-fil-proofs", rev = "filecoin-proofs-v9.0.1-revert-deps-hotfix" }
#storage-proofs-porep = { git = "https://github.com/filecoin-project/rust-fil-proofs", rev = "filecoin-proofs-v9.0.1-revert-deps-hotfix" }
#storage-proofs-post = { git = "https://github.com/filecoin-project/rust-fil-proofs", rev = "filecoin-proofs-v9.0.1-revert-deps-hotfix" }
#fr32 = { git = "https://github.com/filecoin-project/rust-fil-proofs", rev = "filecoin-proofs-v9.0.1-revert-deps-hotfix" }
#filecoin-proofs = { git = "https://github.com/filecoin-project/rust-fil-proofs", rev = "filecoin-proofs-v9.0.1-revert-deps-hotfix" }
#filecoin-hashers = { git = "https://github.com/filecoin-project/rust-fil-proofs", rev = "filecoin-proofs-v9.0.1-revert-deps-hotfix" }
#neptune = { git = "https://github.com/filecoin-project/neptune", rev = "v4.0.0-revert-deps-hotfix" }

storage-proofs-core = { path = '../../../../lin-rust-fil-proofs/storage-proofs-core' }
storage-proofs-porep = { path = '../../../../lin-rust-fil-proofs/storage-proofs-porep' }
storage-proofs-post = { path = '../../../../lin-rust-fil-proofs/storage-proofs-post' }
fr32 = { path = '../../../../lin-rust-fil-proofs/fr32' }
filecoin-proofs = { package = "filecoin-proofs", path = '../../../../lin-rust-fil-proofs/filecoin-proofs' }
filecoin-hashers = { path = '../../../../lin-rust-fil-proofs/filecoin-hashers' }
neptune = { path = '../../../../neptune' }

merkletree = { path = '../../../../merkletree' }
bellperson = { path = '../../../../lin-bellperson' }
mimalloc = { path = '../../../../mimalloc_rust' }
filecoin-proofs-api = { path = '../../../../rust-filecoin-proofs-api' }
